config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root "home#index"

  resources :blog_posts do
    resources :comments, only: [ :create, :destroy ]
  end

  get "search_user", to: "home#index"

  resources :users, only: [ :show ]

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :title, presence: true
    validates :body, presence: true

    def self.ransackable_attributes(auth_object = nil)
        [ "title" ]
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog_post
  belongs_to :user

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blog_posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Devise modules
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Validations
  validates :name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: :modern
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
    before_action :set_blog_post, only: [ :show, :edit, :update, :destroy ]
    before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy ]
    before_action :authorized_user, only: [ :edit, :update, :destroy ]


    def show
        @comments = @blog_post.comments.includes(:user)
    rescue ActiveRecord::RecordNotFound
        redirect_to root_path
    end

    def new
        @blog_post = BlogPost.new
    end

    def create
        @blog_post = current_user.blog_posts.build(blog_post_params)
        if @blog_post.save
            redirect_to @blog_post, notice: "Blog post was successfully created."
        else
            render :new, status: :unprocessable_entity, alert: "There was an error creating the blog post."
        end
    end

    def edit
    rescue ActiveRecord::RecordNotFound
        redirect_to root_path
    end

    def update
        if @blog_post.update(blog_post_params)
            redirect_to @blog_post
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @blog_post.destroy
        redirect_to root_path
    end

    private

    def blog_post_params
        params.require(:blog_post).permit(:title, :body)
    end

    def set_blog_post
        @blog_post = BlogPost.find(params[:id])
    end

    def authorized_user
        redirect_to root_path, notice: "Not authorized." unless @blog_post.user == current_user
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [ :destroy ]

  def create
    @comment = current_user.comments.new(comment_params)
    if !@comment.save
      flash[:notice] = @comment.errors.full_messages.to_sentence
    end

    redirect_to blog_post_path(params[:blog_post_id])
  end

  def destroy
    @comment.destroy
    redirect_to blog_post_path(params[:blog_post_id]), notice: "Comment was successfully deleted."
  end

  def comment_user
    @comment_user = User.where(user_id: comment.id).includes(:user)
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content).merge(blog_post_id: params[:blog_post_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    include Pagy::Backend

    def index
      @q = BlogPost.ransack(params[:q])
      if params[:q].present? && params[:q][:title_cont].present?
        @pagy, @blog_posts = pagy(@q.result.order(created_at: :desc))
      else
        @pagy, @blog_posts = pagy(BlogPost.order(created_at: :desc))
      end
    rescue Pagy::OverflowError
      redirect_to root_path(page: 1)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private

    def sign_up_params
      params.require(:user).permit(:name, :last_name, :email, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:name, :last_name, :email, :password, :password_confirmation, :current_password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :show ]

  def show
    @user_posts = BlogPost.where(user_id: @user.id).includes(:user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post, html: { class: "w-full flex flex-col gap-4" } do |form| %>
  <% if form.object.errors.any? %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <% form.object.errors.full_messages.each do |message| %>
        <span class="block sm:inline"><%= message %></span>
      <% end %>
    </div>
  <% end %>
  <span class="text-3xl pb-4"><%=form_title%></span>
  <div class="w-full flex flex-col">
    <%= form.label :title, class: "block mb-2 text-sm font-medium text-gray-900" %>
    <%= form.text_field :title, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %>
  </div>

  <div class="w-full flex flex-col">
    <%= form.label :body, class: "block mb-2 text-sm font-medium text-gray-900" %>
    <%= form.text_area :body, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %>
  </div>

  <div class="actions">
    <%= form.submit "#{button_text}", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded w-fit cursor-pointer" %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<main class="flex items-center justify-center h-screen">
    <div class="bg-white rounded-lg shadow border-gray-200 border px-6 py-8 lg:w-[700px]">
        <%= render partial: "form", locals: {blog_post: @blog_post, form_title: "Update blog post", button_text: "Update"} %>
    </div>
</main>

app/views/blog_posts/new.html.erb
<main class="flex items-center justify-center h-screen">
  <div class="bg-white rounded-lg shadow border-gray-200 border px-6 py-8 lg:w-[500px]">
    <%= render partial: "form", locals: {blog_post: @blog_post, form_title: "Create new post", button_text: "Create"} %>
</div>
</main>

app/views/blog_posts/show.html.erb
<main class="w-full flex flex-col items-center">
  <div class="w-1/2 my-12">
    <div class="border-b border-neutral-200 flex flex-col gap-2 items-center">
      <span class="text-4xl"><%= @blog_post.title %></span>
      <div class="text-xl pt-2 flex gap-2 items-center">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
        </svg>

        <% if @blog_post.user %>
          <%= link_to @blog_post.user.full_name, user_path(@blog_post.user), class: "text-blue-500 hover:text-blue-700" %>
        <% else %>
          <%= "Unknown User" %>
        <% end %>
      </div>
      <div class="flex pb-2 justify-center">
        <main class="flex items-center gap-4">
          <div class="flex gap-2 text-gray-600">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
            </svg>
            <%= @blog_post.created_at.strftime("%d %B %Y %H:%M") %>
          </div>
          <div class="flex gap-2 text-gray-600">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125" />
            </svg>
            <%= @blog_post.updated_at.strftime("%d %B %Y %H:%M") %>
          </div>
        </main>
      </div>
      <% if @blog_post.user == current_user %>
        <div class="flex gap-2">
          <%= link_to "Edit", "/blog_posts/#{@blog_post.id}/edit", class: "text-stone-800 border border-blue-600 hover:border-blue-800 hover:bg-blue-200 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 mb-2 text-center cursor-pointer" %>
          <%= link_to "Delete", "/blog_posts/#{@blog_post.id}", data: { turbo_confirm: "Are you sure you want to delete that post?", turbo_method: :delete }, class: "text-stone-800 border border-red-600 hover:border-red-800 hover:bg-red-200 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 mb-2 text-center cursor-pointer" %>
        </div>
      <% end %>
    </div>
    <p class="py-4"><%= @blog_post.body %></p>
    <div class="flex flex-col gap-2">
      <% if user_signed_in? %>
        <%= render partial: 'comments/form', locals: { blog_post: @blog_post } %>
      <% end %>
      <p><%= render 'comments/comments', comments: @blog_post.comments %></p>
    </div>
  </div>
</main>

app/views/comments/_comments.html.erb
<div class="comments-container space-y-4">
  <% sorted_comments = @comments.sort.reverse %>
  <% sorted_comments.each do |comment| %>
    <article class="comment border border-gray-300 p-4 rounded-lg flex justify-between">
      <div>
        <div class="flex items-center gap-4 mb-2">
          <%= link_to comment.user.full_name, user_path(comment.user), class: "text-blue-500 hover:text-blue-700" %>
          <small class="block text-gray-600"><%= comment.created_at.strftime("%d %B %Y %H:%M") %></small>
        </div>
        <p class="text-gray-800"><%= comment.content %></p>
      </div>
      <% if comment.user == current_user %>
        <%= button_to 'Delete', blog_post_comment_path(comment.blog_post, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-red-500 bg-transparent hover:text-red-700 cursor-pointer' %>
      <% end %>
    </article>
  <% end %>
</div>

app/views/comments/_form.html.erb
<div class="comment-form mt-6">
  <%= form_with(model: [ blog_post, blog_post.comments.build ], local: true) do |form| %>
    <div class="mb-4">
      <%= form.label :content, class: "block text-gray-700" %>
      <%= form.text_area :content, class: "w-full h-24 p-2 border border-gray-300 rounded-lg" %>
    </div>
    <div>
      <%= form.submit "Add Comment", class: "bg-blue-500 text-white py-2 px-4 rounded-lg hover:bg-blue-700 cursor-pointer" %>
    </div>
  <% end %>
</div>

app/views/home/_header.html.erb
<nav
    class="z-20 flex shrink-0 grow-0 justify-around gap-4 border-t border-gray-200 bg-white/50 p-2.5 shadow-lg backdrop-blur-lg fixed top-2/4 -translate-y-2/4 left-6 min-h-[auto] min-w-[64px] flex-col rounded-lg border text-white"
    >
    <%= link_to root_path, class: "flex aspect-square min-h-[32px] w-16 flex-col items-center justify-center gap-1 rounded-md p-1.5 text-stone-900 hover:text-blue-700" do %>
        <!-- HeroIcon - User -->
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 21v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21m0 0h4.5V3.545M12.75 21h7.5V10.75M2.25 21h1.5m18 0h-18M2.25 9l4.5-1.636M18.75 3l-1.5.545m0 6.205 3 1m1.5.5-1.5-.5M6.75 7.364V3h-3v18m3-13.636 10.5-3.819" />
        </svg>
        <small class="text-center text-xs font-medium"> Home </small>
    <% end %>
    <% if user_signed_in? %>
        <%= link_to "/blog_posts/new", class: "flex aspect-square min-h-[32px] w-16 flex-col items-center justify-center gap-1  rounded-md p-1.5 text-stone-900 hover:text-blue-700" do %>
            <!-- HeroIcon - User -->
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"    class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
            </svg>

            <small class="text-center text-xs font-medium"> New post </small>
        <% end %>
        <%= link_to user_path(current_user), class: "flex aspect-square min-h-[32px] w-16 flex-col items-center justify-center gap-1  rounded-md p-1.5 text-stone-900 hover:text-blue-700" do %>
            <!-- HeroIcon - User -->
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
            </svg>

            <small class="text-center text-xs font-medium"> Profile </small>
        <% end %>
        <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "flex aspect-square min-h-[32px] w-16 flex-col items-center justify-center gap-1  rounded-md p-1.5 text-stone-900 hover:text-blue-700" do %>
            <!-- HeroIcon - User -->
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 9V5.25A2.25 2.25 0 0 1 10.5 3h6a2.25 2.25 0 0 1 2.25 2.25v13.5A2.25 2.25 0 0 1 16.5 21h-6a2.25 2.25 0 0 1-2.25-2.25V15m-3 0-3-3m0 0 3-3m-3 3H15" />
            </svg>
          
            <small class="text-center text-xs font-medium"> Logout </small>
        <% end %>
    <% else %>
        <%= link_to new_user_session_path, class: "flex aspect-square min-h-[32px] w-16 flex-col items-center justify-center gap-1  rounded-md p-1.5 text-stone-900 hover:text-blue-700" do %>
            <!-- HeroIcon - User -->
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 9V5.25A2.25 2.25 0 0 1 10.5 3h6a2.25 2.25 0 0 1 2.25 2.25v13.5A2.25 2.25 0 0 1 16.5 21h-6a2.25 2.25 0 0 1-2.25-2.25V15M12 9l3 3m0 0-3 3m3-3H2.25" />
            </svg>

            <small class="text-center text-xs font-medium"> Login </small>
        <% end %>
    <% end %>
</nav>

app/views/home/_navbar.html.erb
<%= search_form_for @q, url: search_user_path, class: "w-1/2 mx-auto" do |f| %>
  <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only">Search</label>
  <div class="relative">
    <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
      <svg class="w-4 h-4 text-gray-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
      </svg>
    </div>
    <%= f.search_field :title_cont, id: "default-search", class: "block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500", placeholder: "Search Posts by title..." %>
    <button type="submit" class="text-white absolute end-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 cursor-pointer">Search</button>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="w-full flex justify-center items-center py-4">
  <%= render "home/navbar" %>
</div>
<main class="w-full flex flex-col items-center my-4">
  <div class="w-1/2">
    <% if @blog_posts.present? %>
      <% @blog_posts.each do |post| %>
        <div class="bg-white rounded-lg shadow border-gray-200 border w-full px-6 py-8 mb-4">
          <h1 class="text-4xl font-extrabold text-blue-900">
            <%= link_to post.title, post, class: "text-blue-500 hover:text-blue-700" %>
          </h1>
          <div class="flex items-center gap-4 mt-2">
            <div class="flex justify-center items-center gap-2 text-gray-600">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
              </svg>
              <%= post.created_at.strftime("%d %B %Y %H:%M") %>
            </div>
            <div class="flex justify-center text-gray-600 gap-2 items-center">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
              </svg>
              <% if post.user %>
                <%= link_to post.user.full_name, user_path(post.user), class: "text-blue-500 hover:text-blue-700" %>
              <% else %>
                <%= "Unknown User" %>
              <% end %>
            </div>
          </div>
          <p class="text-gray-700 mt-2 line-clamp-3">
            <%= post.body %>
          </p>
        </div>
      <% end %>

      <%== pagy_nav(@pagy) if @pagy && @pagy.pages > 1 %>
    <% else %>
      <span class="text-3xl pb-4 flex justify-center">No blog posts yet!</span>
    <% end %>
  </div>
</main>

app/views/layouts/_alert.html.erb
<div id="alert" class="flex flex-col min-w-fit w-1/2 fixed bottom-2 left-1/2 transform -translate-x-1/2 p-4 mb-4 text-sm text-orange-900 rounded-lg bg-orange-100/50 text-center border border-orange-500 role="alert">
  <span class="font-medium"><%= alert %></span>
  <span>Change a few things up and try submitting again.</span>
</div>

app/views/layouts/_notice.html.erb
<div id="alert" class="flex flex-col min-w-fit w-1/2 fixed bottom-2 left-1/2 transform -translate-x-1/2 p-4 mb-4 text-sm text-center text-green-900 rounded-lg bg-green-100/50 border border-green-500 role="alert">
  <span class="font-medium"><%= notice %></span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= csp_meta_tag %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
  <%= favicon_link_tag 'blogging_1187544.png', type: 'image/png' %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <%= render "home/header" %>
  <% if alert %>
    <%= render 'layouts/alert' %>
  <% end %>
  <% if notice %>
    <%= render 'layouts/notice' %>
  <% end %>
  
  <%= yield %>

</body>
</html>

app/views/users/show.html.erb
<main class="flex flex-col items-center w-full my-12">
  <div class="w-1/2">
    <%= button_to :back, class: "w-fit mb-4 cursor-pointer flex gap-2", method: :get do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M9 15 3 9m0 0 6-6M3 9h12a6 6 0 0 1 0 12h-3" />
      </svg>
      Back
    <% end %>
    <div class="bg-white rounded-lg shadow border-gray-200 border px-6 py-8">
      <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl">
          User Profile
        </h1>
        <div class="w-full flex flex-col gap-4">
          <div class="w-full flex flex-col">
            <span class="block mb-2 text-sm font-medium text-gray-900">Name</span>
            <span class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg p-2.5"><%= @user.name %></span>
          </div>
          <div class="w-full flex flex-col">
            <span class="block mb-2 text-sm font-medium text-gray-900">Last Name</span>
            <span class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg p-2.5"><%= @user.last_name %></span>
          </div>
          <div class="w-full flex flex-col">
            <span class="block mb-2 text-sm font-medium text-gray-900">Email</span>
            <span class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg p-2.5"><%= @user.email %></span>
          </div>
        </div>
        <% if @user == current_user %>
          <div class="actions mt-4">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded w-fit cursor-pointer" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="flex flex-col items-center mt-8">
      <h2 class="text-2xl font-bold leading-tight tracking-tight w-full text-gray-900 md:text-3xl mb-4">
        User Posts
      </h2>
      <% @user_posts.each do |blog_post| %>
        <div class="bg-white rounded-lg shadow border-gray-200 border w-full px-6 py-4 mb-4">
          <h3 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl">
            <%= link_to blog_post.title, blog_post_path(blog_post), class: "text-blue-500 hover:text-blue-700" %>
          </h3>
          <p class="text-gray-700 mt-2 line-clamp-2">
            <%= blog_post.body %>
          </p>
          <div class="text-sm text-gray-600 mt-2">
            <%= blog_post.created_at.strftime("%d %B %Y %H:%M") %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</main>